---
title: "Reporte Técnico Proyecto Bonos de Carbono"
subtitle: "[Proyecto] - Lote [x]"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Línea Base

Vegetación
La vegetación presente en este lote corresponde al tipo forestal [tipo forestal catastro], abarcando [x] ha correspondientes a un [x]% de la superficie del lote. Además, el lote cuenta con [x] ha de [Cobertura 2] y [x] ha de [Cobertura 3], correspondientes a un [x]% y [x]% de la superficie del lote, respectivamente (CONAF, [Año]).

De acuerdo con Luebert y Pliscoff (2017), el lote pertenece al piso vegetacional [piso vegetacional] y la formación vegetacional [formación vegetacional]. 

Clima
El clima predominante del lote corresponde a [nombre clima] ([sigla clima]) de acuerdo con la clasificación Koppen-Geiger (Beck et al., 2023).

LiDAR 
Se obtuvieron el día [fecha de vuelos] utilizando como punto de referencia geodésico la siguiente coordenada [coordenada geográfica base] procesada en modalidad PPP. Los vuelos fueron realizados a una altura de [altura de vuelo] y velocidad [velocidad  de vuelo] con una densidad de [densidad de puntos] puntos/m2.

De estos vuelos se derivaron un modelo digital de terreno, que corresponde a la elevación del suelo del terreno, un modelo digital de superficie, que corresponde a la superficie descrita por todos lo objetos sobre el suelo, y un modelo de altura de dosel de la vegetación, que describe la altura que tiene la vegetación en el lote.

Modelo Digital de Terreno (DTM)
La topografía del lote [x] cuenta con una elevación mínima, media y máxima de [z] m, [z] m y [z] m, respectivamente.

[Mapa] 
Figura 2. Modelo digital de terreno del lote [x]. 

Modelo Digital de Superficie (DSM)
Los objetos sobre la superficie del suelo en el lote [x] cuentan con una elevación mínima, media y máxima de [z] m, [z] m y [z] m, respectivamente.

[Mapa] 
Figura 3. Modelo digital de superficie del lote [x]. 

Modelo de Altura del Dosel de la Vegetación (CHM)
La vegetación presente en el lote [x] posee una altura promedio de [x] m, con un valor de altura máxima de [x] m.

[Mapa] 
Figura 4. Modelo de altura del dosel de la vegetación del lote [x]. 


Biomasa Aérea y Carbono Vegetal Almacenado
La vegetación presente en el lote [x] posee una biomasa aérea promedio de [x] ton por hectárea, lo cual se traduce en [x] ton de Carbono promedio por ha almacenadas. Por otro lado, la biomasa aérea total acumulada en el lote [x] alcanza la cifra de [x] ton por hectárea, lo cual se traduce en [x] ton de Carbono por ha totales almacenadas.

[Mapa] 
Figura 5. Biomasa aérea del lote [x]. 

[Mapa] 
Figura 6. Carbono vegetal almacenado del lote [x]. 

Identificación de Árboles (Tree-ID)
En el lote [x] existen un total de [x] árboles aproximadamente.


## Áreas de Representatividad